#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["GFTFluxoCaixa.Api/GFTFluxoCaixa.Api.csproj", "GFTFluxoCaixa.Api/"]
RUN dotnet restore "GFTFluxoCaixa.Api/GFTFluxoCaixa.Api.csproj"
COPY . .
WORKDIR "/src/GFTFluxoCaixa.Api"
RUN dotnet build "GFTFluxoCaixa.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "GFTFluxoCaixa.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "GFTFluxoCaixa.Api.dll"]